name: "Release: Publish"
run-name: "Release: ${{ inputs.tag }}"

on:
  workflow_dispatch:
      inputs:
          tag:
              required: true
              type: string

jobs:
  ReleaseCheck:
    uses: aws-deadline/.github/.github/workflows/reusable_release_check.yml@mainline
    secrets:
      EMAIL: ${{ secrets.EMAIL }}
    with:
      tag: ${{ inputs.tag }}

  UnitTests:
    needs: ReleaseCheck
    name: Unit and Integration Tests
    uses: ./.github/workflows/code_quality.yml
    with:
      tag: ${{inputs.tag}}

  PreRelease:
      needs: [ReleaseCheck, UnitTests]
      uses: aws-deadline/.github/.github/workflows/reusable_prerelease.yml@mainline
      secrets: inherit
      with:
          tag: ${{inputs.tag}}

  BuildAndStageInstallers:
    needs: PreRelease
    uses: aws-deadline/.github/.github/workflows/reusable_stage_installers.yml@mainline
    secrets: inherit
    permissions:
      id-token: write
    with:
      project_name: ${{ github.event.repository.name }}
      tag: ${{ inputs.tag }}
      oses: "['Linux', 'Windows', 'MacOS']"

  IsCondaReady:
    needs: BuildAndStageInstallers
    runs-on: ubuntu-latest
    environment: release
    name: “Is the Conda Package available in all ProdWaves and have you ran any required manual tests?”
    steps:
      - run: |
         :

  Release:
      needs: IsCondaReady
      uses: aws-deadline/.github/.github/workflows/reusable_release.yml@mainline
      secrets: inherit
      with:
          tag: ${{inputs.tag}}
  
  Publish:
      needs: Release
      uses: aws-deadline/.github/.github/workflows/reusable_publish_python.yml@mainline
      secrets: inherit
      with:
          tag: ${{inputs.tag}}
  # PyPI does not support reusable workflows yet
  # # See https://github.com/pypi/warehouse/issues/11096
  PublishToPyPI:
      needs: Publish
      runs-on: ubuntu-latest
      environment: release
      permissions:
        id-token: write
      steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade hatch
      - name: Build
        run: hatch -v build
      # # See https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-pypi
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

