name: "Release: Publish"
run-name: "Release"

on:
  workflow_dispatch:

concurrency:
  group: release

permissions:
  contents: read

jobs:
  PublishToPyPI:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install --upgrade hatch
    - name: Build
      run: hatch -v build

